service: money-manager
app: money-manager-users

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  region: ${opt:region, 'us-east-1'}
  environment:
    DYNAMODB_TABLE: ${self:app}-${self:provider.stage}
    ALLOWED_ORIGINS: '*'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
          - dynamodb:Scan
          - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  create:
    handler: bin/users/create
    package:
      include:
        - ./bin/users/create
    events:
      - http:
          path: users
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(./user_create.json)}

custom:
    apiAllowedOrigins: "'${self:provider.environment.ALLOWED_ORIGINS}'"

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
            gatewayresponse.header.Access-Control-Allow-Origin: ${self:custom.apiAllowedOrigins}
            gatewayresponse.header.Access-Control-Allow-Headers: ${self:custom.apiAllowedOrigins}
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: ${self:custom.apiAllowedOrigins}
          gatewayresponse.header.Access-Control-Allow-Headers: ${self:custom.apiAllowedOrigins}
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

plugins:
  - serverless-sam
